name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Check Code Formatting
        run: flutter format --set-exit-if-changed .

      - name: Run Lint
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test

      - name: Run Integration Tests
        run: flutter drive --target=test_driver/app.dart

      - name: Security Check
        run: flutter pub outdated --mode=null-safety

      - name: Build App
        run: flutter build apk --debug

