name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Lint
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test

      - name: Build App
        run: flutter build apk --debug

    #  - name: Deploy (utfpr_bmi)
    #   run: deploy_command_here
